#view resovler
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5 # support html5
    encoding: utf-8
    cache: false
server:
  port: 8080